version: '3.2'

services:
  ace-node-js:
    container_name: ace-node-js
    image: ace-node-js:latest
    user: node
    command: "npm start"
    working_dir: /home/node/app
    environment: 
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "5555:5555"

